import Head from "next/head";
import Image from "next/image";
import deved from "../public/Avatar.png";
import design from "../public/design.png";
import code from "../public/code.png";
import consulting from "../public/consulting.png";
import web1 from "../public/bricomarché.png";
import web2 from "../public/MON-CV.png";
import web3 from "../public/slide.png";
import { AiOutlineEye } from "react-icons/ai";
import { AiOutlineLinkedin, AiOutlineInstagram } from "react-icons/ai";
import { AiFillGithub } from "react-icons/ai";
import { useState } from "react";

export default function Home() {
  const [darkmode, setDarkmode] = useState(false);
  return (
    <div className={darkmode ? "dark" : ""}>
      <Head>
        <title>Junior portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <div>
              <h1 className="text-xl capitalize dark:text-white ">Baracus</h1>
            </div>
            <ul className="flex items-center">
              <li>
                <AiOutlineEye
                  className="cursor-pointer text-xl dark:text-white hover:scale-125  hover:text-teal-800"
                  onClick={() => setDarkmode(!darkmode)}
                />
              </li>
              <li>
                <a
                  href="#"
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"
                >
                  Resume
                </a>
              </li>
              <li></li>
              <li></li>
            </ul>
          </nav>
          <div className="text-center p-10 ">
            <h2 className="text-5xl py2 text-teal-600 font-medium md:text-6xl">
              Guinier Junior
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl dark:text-white">
              Apprenti Developpeur web/mobile et design
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto dark:text-white">
              Actuellement à la recherche d'une alternance en entreprise dans le
              cadre de ma formation, développeur web-mobile 4 jours en
              entreprise et 1 jour en formation.
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
            <a
              href="https://www.linkedin.com/in/junior-guinier/"
              target="_blank"
              className="cursor-pointer target: "
            >
              <AiOutlineLinkedin className="dark:text-white hover:scale-105 delay-200 hover:text-teal-800" />
            </a>

            <a href="https://github.com/BaracusHanson" target="_blank">
              <AiFillGithub className="dark:text-white hover:scale-105 delay-200 hover:text-teal-800" />
            </a>
            <a href="https://www.instagram.com/b0racus/" target="_blank">
              <AiOutlineInstagram className="dark:text-white hover:scale-105 delay-200 hover:text-teal-800" />
            </a>
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96">
            <Image src={deved} layout="fill" objectFit="cover" />
          </div>
        </section>
        <section className="">
          <div className="invisible">
            <h3 className="text-3xl py-1 ">Mes Services</h3>
            <p className="text-md py-2 leading-8 text-gray-800"></p>
            <p className="text-md py-2 leading-8 text-gray-800">
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde amet
              nam <span className="text-teal-500">quam</span> ea modi! Lorem
              ipsum dolor sit amet consectetur adipisicing elit. Unde{" "}
              <span className="text-teal-500">amet adipisicing</span> nam autem
              quam ea modi adipisicing elit. Unde amet!
            </p>
          </div>

          <div className="lg:flex justify-evenly gap-10 ">
            <div className="text-center shadow-lg p-12 rounded-xl my-10   dark:bg-white">
              <Image src={design} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2">
                Des designs éblouissants
              </h3>
              <p className="py-2">
                Créer des designs élégants adaptés à vos besoins
              </p>
              <h4 className="py-4 text-teal-600">Mes outils de design</h4>
              <p className="text-gray-800 py-1">Figma</p>
              <p className="text-gray-800 py-1">Spline</p>
              <p className="text-gray-800 py-1">Balsamiq</p>
              <p className="text-gray-800 py-1">Illustrator</p>
            </div>

            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white">
              <Image src={code} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2">
                Un flux de travail solide
              </h3>
              <p className="py-2">
                Créer des intégration fidèles aux attentes clients
              </p>
              <h4 className="py-4 text-teal-600">Mes langages</h4>
              <p className="text-gray-800 py-1">html5</p>
              <p className="text-gray-800 py-1">css3</p>
              <p className="text-gray-800 py-1">javascript</p>
              <p className="text-gray-800 py-1">vba</p>
            </div>

            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white">
              <Image src={consulting} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2">
                La pointe de la technologie
              </h3>
              <p className="py-2">
                Créer une expérience utilisateur bouleversante
              </p>
              <h4 className="py-4 text-teal-600">Mes frameworks</h4>
              <p className="text-gray-800 py-1">tailwind</p>
              <p className="text-gray-800 py-1">react js</p>
            </div>
          </div>
        </section>

        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white">Portfolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-white">
              Ayant une forte appétence pour le développement{" "}
              <span className="text-teal-500">web</span> et plus
              particulièrement le <span className="text-teal-500">design</span>{" "}
              et la création <span className="text-teal-500">3D</span>, il est
              important pour moi d'améliorer mes compétences dans ces trois
              dommaines
            </p>
            <p className="invisible">J'offre une large gamme de Services.</p>
          </div>

          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1">
              <a
                href="https://www.figma.com/proto/iSzpCZeRSGbKFN56rsmP5J/bricomarch%C3%A9?page-id=0%3A1&node-id=10%3A441&viewport=365%2C1020%2C0.39&scaling=contain&starting-point-node-id=10%3A414"
                target="_blank"
              >
                {" "}
                <Image
                  src={web1}
                  className="rounded-lg object-cover hover:scale-105"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                />
              </a>
            </div>

            <div className="basis-1/3 flex-1">
              <a
                href="https://my.spline.design/untitled-e277c3226448eac1b59be263a502c1ee/"
                target="_blank"
              >
                {" "}
                <Image
                  src={web2}
                  className="rounded-lg object-cover hover:scale-105 "
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                />
              </a>
            </div>

            <div className="basis-1/3 flex-1">
              <a href="https://baracushanson.github.io/slide/" target="_blank">
                {" "}
                <Image
                  src={web3}
                  className="rounded-lg object-cover hover:scale-105 "
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                />
              </a>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
